name: sports-affiliate-api
region: nyc

# This DigitalOcean App Platform configuration deploys the sports affiliate tracker
# backend. It builds the Node.js application located in the `affiliate-backend`
# directory and runs it as a service listening on port 8080. The configuration
# includes environment variables for MongoDB and OpenAI credentials along with
# a link back to the frontend. Remove any unused or placeholder values before
# deployment.
services:
  - name: backend
    source_dir: affiliate-backend
    run_command: node src/index.js
    build_command: npm ci --production
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xs
    http_port: 8080
    routes:
      - path: /
    health_check:
      http_path: /health
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: MONGODB_URI
        value: "your_mongodb_connection_string"
        type: SECRET
      - key: OPENAI_API_KEY
        value: "your_openai_api_key"
        type: SECRET
      - key: FRONTEND_URL
        value: "https://ripcityticketdispatch.works"

# The domain definitions below direct the primary apex domain and a subdomain
# to the backend service. Update these to match your actual domain names and
# Cloudflare configuration. If you plan to host the React frontend separately
# (e.g. on a static hosting service), point the root domain to that site and
# use a subdomain (e.g. api.) for the backend.
domains:
  - domain: api.ripcityticketdispatch.works
    type: PRIMARY
    wildcard: false
    zone: ripcityticketdispatch.works
  - domain: ripcityticketdispatch.works
    type: ALIAS
    wildcard: false
    zone: ripcityticketdispatch.works