# Generated by Django 5.2.4 on 2025-07-28 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('blackjack', 'Blackjack'), ('rps', 'Rock Paper Scissors'), ('dice', 'Dice Game')], max_length=20)),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('game_state', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='DiceGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_balance', models.IntegerField(default=1000)),
                ('current_bet', models.IntegerField(default=0)),
                ('last_roll', models.JSONField(default=list)),
                ('total_games', models.IntegerField(default=0)),
                ('games_won', models.IntegerField(default=0)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='games.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='BlackjackGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_hand', models.JSONField(default=list)),
                ('dealer_hand', models.JSONField(default=list)),
                ('deck', models.JSONField(default=list)),
                ('player_score', models.IntegerField(default=0)),
                ('dealer_score', models.IntegerField(default=0)),
                ('game_status', models.CharField(default='playing', max_length=20)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='games.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='RPSGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_moves', models.JSONField(default=list)),
                ('computer_moves', models.JSONField(default=list)),
                ('results', models.JSONField(default=list)),
                ('player_score', models.IntegerField(default=0)),
                ('computer_score', models.IntegerField(default=0)),
                ('pattern_data', models.JSONField(default=dict)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='games.gamesession')),
            ],
        ),
    ]
