name: rip-city-api
region: nyc
services:
- name: api
  source_dir: affiliate-backend
  github:
    repo: Mazzlabs/ripcityticketdispatch.works
    branch: main
    deploy_on_push: true
  run_command: node src/index.js
  build_command: npm ci
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xs
  http_port: 8080
  routes:
  - path: /
  health_check:
    http_path: /health
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: MONGODB_URI
    value: "${mongodb.DATABASE_URL}"
    type: SECRET
  - key: TICKETMASTER_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: FRONTEND_URL
    value: "https://ripcityticketdispatch.works"
  - key: CORS_ORIGINS
    value: "https://ripcityticketdispatch.works,https://api.ripcityticketdispatch.works"

- name: frontend
  source_dir: affiliate-frontend
  github:
    repo: Mazzlabs/ripcityticketdispatch.works
    branch: main
    deploy_on_push: true
  build_command: npm ci && npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xs
  http_port: 3000
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: REACT_APP_API_URL
    value: "https://api.ripcityticketdispatch.works"

databases:
- engine: MONGODB
  name: mongodb
  version: "5"

domains:
- domain: api.ripcityticketdispatch.works
  type: PRIMARY
  wildcard: false
  zone: ripcityticketdispatch.works
- domain: ripcityticketdispatch.works
  type: ALIAS
  wildcard: false
  zone: ripcityticketdispatch.works
