name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '18.x'

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: |
          affiliate-backend/package-lock.json
          affiliate-frontend/package-lock.json
    
    - name: Install backend dependencies
      run: |
        cd affiliate-backend
        npm ci
        
    - name: Install frontend dependencies
      run: |
        cd affiliate-frontend
        npm ci
        
    - name: Lint backend code
      run: |
        cd affiliate-backend
        npm run lint || echo "No lint script found, skipping..."
        
    - name: Lint frontend code
      run: |
        cd affiliate-frontend
        npm run lint || echo "No lint script found, skipping..."
        
    - name: Test backend
      run: |
        cd affiliate-backend
        npm test || echo "No tests found, skipping..."
        
    - name: Test frontend
      run: |
        cd affiliate-frontend
        npm test -- --coverage --passWithNoTests
      env:
        CI: true
        
    - name: Build frontend
      run: |
        cd affiliate-frontend
        npm run build

  deploy:
    name: Deploy to DigitalOcean
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        
    - name: Deploy to DigitalOcean App Platform
      run: |
        # Update app configuration with secrets from GitHub
        doctl apps update ${{ secrets.DIGITALOCEAN_APP_ID }} --spec .do/app.yaml
        
        # Trigger a new deployment
        doctl apps create-deployment ${{ secrets.DIGITALOCEAN_APP_ID }}
        
    - name: Notify deployment status
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "✅ Deployment successful"
        else
          echo "❌ Deployment failed"
          exit 1
        fi

  security-scan:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: Audit backend dependencies
      run: |
        cd affiliate-backend
        npm audit --audit-level=high
        
    - name: Audit frontend dependencies
      run: |
        cd affiliate-frontend
        npm audit --audit-level=moderate || true # Allow moderate vulnerabilities for now